### ISSUE TITLE
error: 'EINVAL' was not declared in this scope

### ISSUE THREAD

**Issue by l4es** [DISTORTEC/distortosExamples#1]
I followed the README to make a build for STM32F4 target but I had following error:

```
khang@Thinkpad-T480s-OUVPDR-1805 ~/Workspace/Edu/RTOS-Development/distortosExamples (master) $ make
[  0%] CXX     distortos/source/C-API/C-API-Semaphore.cpp
distortos/source/C-API/C-API-Semaphore.cpp: In function 'int distortos_Semaphore_construct_1(distortos_Semaphore*, unsigned int, unsigned int)':
distortos/source/C-API/C-API-Semaphore.cpp:34:10: error: 'EINVAL' was not declared in this scope
   return EINVAL;
          ^
distortos/source/C-API/C-API-Semaphore.cpp: In function 'int distortos_Semaphore_destruct(distortos_Semaphore*)':
distortos/source/C-API/C-API-Semaphore.cpp:43:10: error: 'EINVAL' was not declared in this scope
   return EINVAL;
          ^
distortos/source/C-API/C-API-Semaphore.cpp: In function 'int distortos_Semaphore_getValue(const distortos_Semaphore*, unsigned int*)':
distortos/source/C-API/C-API-Semaphore.cpp:53:10: error: 'EINVAL' was not declared in this scope
   return EINVAL;
          ^
distortos/source/C-API/C-API-Semaphore.cpp: In function 'int distortos_Semaphore_post(distortos_Semaphore*)':
distortos/source/C-API/C-API-Semaphore.cpp:63:10: error: 'EINVAL' was not declared in this scope
   return EINVAL;
          ^
distortos/source/C-API/C-API-Semaphore.cpp: In function 'int distortos_Semaphore_tryWait(distortos_Semaphore*)':
distortos/source/C-API/C-API-Semaphore.cpp:72:10: error: 'EINVAL' was not declared in this scope
   return EINVAL;
          ^
distortos/source/C-API/C-API-Semaphore.cpp: In function 'int distortos_Semaphore_tryWaitFor(distortos_Semaphore*, int64_t)':
distortos/source/C-API/C-API-Semaphore.cpp:81:10: error: 'EINVAL' was not declared in this scope
   return EINVAL;
          ^
distortos/source/C-API/C-API-Semaphore.cpp: In function 'int distortos_Semaphore_tryWaitUntil(distortos_Semaphore*, int64_t)':
distortos/source/C-API/C-API-Semaphore.cpp:90:10: error: 'EINVAL' was not declared in this scope
   return EINVAL;
          ^
distortos/source/C-API/C-API-Semaphore.cpp: In function 'int distortos_Semaphore_wait(distortos_Semaphore*)':
distortos/source/C-API/C-API-Semaphore.cpp:99:10: error: 'EINVAL' was not declared in this scope
   return EINVAL;
          ^
distortos/Makefile:263: recipe for target 'output/distortos/source/C-API/C-API-Semaphore.o' failed
make: *** [output/distortos/source/C-API/C-API-Semaphore.o] Error 1
```
Could you tell me what is wrong?

Thanks,

**Comment by FreddieChopin** [comment]
Interesting... What toolchain are you using? Type and exact version? Generally it is highly recommended to use https://github.com/FreddieChopin/bleeding-edge-toolchain , as it has properly disabled C++ exceptions at the level of the toolchain libraries (libstdc++v3). The code of distortos (and examples) is tested with Travis-CI against GCC versions 5, 6, 7 and 8 (and by that against quite a lot of versions of newlib), so the error is really surprising, as it usually is related to the different versions of newlib. The usual "solution" is to just put `#include <cerrno>` in the file which causes the error, but I would really like to know why you see the problem while it was not spotted earlier.

Using the "official" toolchain from ARM will probably work in most of the cases, but not necessarily all, that's why I don't really recommend that combination - it is not tested at all.

**Comment by l4es** [comment]
Hi, 
I'm using the prebuilt toolchain suggested here: http://www.freddiechopin.info/en/download/category/11-bleeding-edge-toolchain
$ /opt/gcc-arm-none-eabi-4_8-141002-linux-x64/bin/arm-none-eabi-cpp -v
Using built-in specs.
COLLECT_GCC=/opt/gcc-arm-none-eabi-4_8-141002-linux-x64/bin/arm-none-eabi-cpp
Target: arm-none-eabi
Configured with: /home/freddie/bleeding-edge-toolchain/src/gcc/configure --target=arm-none-eabi --prefix=/home/freddie/bleeding-edge-toolchain/install-native --libexecdir=/home/freddie/bleeding-edge-toolchain/install-native/lib --infodir=/home/freddie/bleeding-edge-toolchain/install-native/share/doc/gcc-arm-none-eabi/info --mandir=/home/freddie/bleeding-edge-toolchain/install-native/share/doc/gcc-arm-none-eabi/man --htmldir=/home/freddie/bleeding-edge-toolchain/install-native/share/doc/gcc-arm-none-eabi/html --pdfdir=/home/freddie/bleeding-edge-toolchain/install-native/share/doc/gcc-arm-none-eabi/pdf --enable-languages=c,c++ --enable-cxx-flags=-fno-exceptions --enable-plugins --disable-decimal-float --disable-libffi --disable-libgomp --disable-libmudflap --disable-libquadmath --disable-libssp --disable-libstdcxx-pch --disable-nls --disable-shared --disable-threads --disable-tls --with-gnu-as --with-gnu-ld --with-newlib --with-headers=yes --with-python-dir=share/gcc-arm-none-eabi --with-sysroot=/home/freddie/bleeding-edge-toolchain/install-native/arm-none-eabi --build=x86_64-linux-gnu --host=x86_64-linux-gnu --with-gmp=/home/freddie/bleeding-edge-toolchain/build-native/host-libs/usr --with-mpfr=/home/freddie/bleeding-edge-toolchain/build-native/host-libs/usr --with-mpc=/home/freddie/bleeding-edge-toolchain/build-native/host-libs/usr --with-isl=/home/freddie/bleeding-edge-toolchain/build-native/host-libs/usr --with-cloog=/home/freddie/bleeding-edge-toolchain/build-native/host-libs/usr --with-libelf=/home/freddie/bleeding-edge-toolchain/build-native/host-libs/usr --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --with-pkgversion='GNU Tools for ARM Embedded Processors / bleeding-edge-toolchain-141002' --with-multilib-list=armv6-m,armv7-m,armv7e-m,armv7-r
Thread model: single

My host; Ubuntu 18.04

BR,

**Comment by FreddieChopin** [comment]
But this one is extremely old - distortos unfortunately does not support versions of GCC earlier than 5 (some time ago it did, but now it does not). Even if you fix the issue with `<cerrno>` there are other places which explicitly error-out when GCC version is below 5.

I strongly suggest you to build the most recent toolchain yourself, using the https://github.com/FreddieChopin/bleeding-edge-toolchain script - either the released "180726" version or directly from the master branch (it has some interesting improvements) - both using GCC 8.2.0. The reasons why I no longer upload Linux binaries, as well as some info what is needed on Ubuntu to build the package can be found in this paragraph of the README.md -> https://github.com/FreddieChopin/bleeding-edge-toolchain#toolchain-for-linux (please install both texinfo and texlive, as now GDB seems to require them in all cases).

If you just want to evaluate distortos, without too much of a hassle with building the toolchains and so on, there are two options that I can think of:
1. Try to use the most recent Linux binary that I uploaded. This would be 160412 5.3.1 and should work with distortos (that's actually the oldest version that I use in Travis-CI). However it is not 100% certain that this package will work with your system (for the reasons, I again refer to the README.md of bleeding-edge-toolchain) and it is actually quite possible that it won't, as even on Travis-CI (which uses Ubuntu 16.04) I have to do some magic to make this toolchain work.
2. You could try downloading the most recent released toolchain built specifically for Travis-CI directly from this link -> http://distortos.org/files/travis-ci/arm-none-eabi-gcc-8.2.0-180726.tar.xz . This toolchain is a compact version of the thing you could build yourself, with no docs and no "nano" libraries (to keep the size down). It should work on your system, but - as above - nothing is guaranteed...

Again - both of these options may not work on your system, the only certain way is to build the toolchain yourself.

I realize that the requirement of bleeding-edge-toolchain is one of the biggest obstacles to using distortos, but for now there is no better alternative. I hope the end result is worth the extra initial effort. The script to build the bleeding-edge-toolchain should be really easy to use, just make sure you have the packages listed in the README.md installed and after some time (expect the process to take something like 30 minutes to 2 hours, depending on hardware specs) you will have your own toolchain ready - just extract and add it to the PATH (;

I hope that these issues are not enough for you too loose interest in distortos. If you decide to build the toolchain yourself (again - highly recommended) just let me know if you experience any issues during the process.

---

BTW - the other obstacle - kconfig-frontends - is being removed "as we speak", as for all 3 repositories there's a cmake-build branch which uses CMake instead of make + shell + kconfig-frontends.

https://github.com/DISTORTEC/distortosExamples/tree/cmake-build

But this is not very stable right now, there will probably be a lot of noise in the repository due to this change of config & build system, however it does work (;

**Comment by l4es** [comment]
Thanks, I'll rebuild the toochain instead of using the pre-built one and let you know if it works.

**Comment by FreddieChopin** [comment]
OK, great - let me know if you experience any problems!

**Comment by l4es** [comment]
Hello Freddie,
I have at the end of build-bleeding-edge-toolchain.sh script's execution:

```
********** Post-cleanup
strip:installNative/lib/gcc/arm-none-eabi/8.2.0/install-tools/mkinstalldirs: File format not recognized
strip:installNative/lib/gcc/arm-none-eabi/8.2.0/install-tools/fixinc.sh: File format not recognized
strip:installNative/lib/gcc/arm-none-eabi/8.2.0/install-tools/mkheaders: File format not recognized
strip:installNative/build-bleeding-edge-toolchain.sh: File format not recognized
********** Package
Killed%        49,2 MiB / 316,3 MiB = 0,156   7,5 MiB/s       0:42             
tar: arm-none-eabi-gcc-8.2.0-180829.tar.xz: Wrote only 4096 of 10240 bytes
tar: Child returned status 137
tar: Error is not recoverable: exiting now
```
Any idea?

**Comment by FreddieChopin** [comment]
The part about "File format not recognized" is expected, normal and nothing to worry about. Why the compression step was killed - I have no idea... Maybe you killed it manually?

**Comment by FreddieChopin** [comment]
BTW - at this stage, if you did not delete anything - you can already use the toolchain which will be available in the "installNative" folder. Everything is fine, the only thing that failed here is the compression of this folder into a nice archive.

**Comment by l4es** [comment]
Hi Freddie,
The newly built toolchain works well.Thanks for your kind support!
BR,
Pascal

**Comment by FreddieChopin** [comment]
Any idea what was the problem yesterday, that the "package" step was killed?

**Comment by l4es** [comment]
It was problem of strip. And it is said that because the files being stripped are scripts instead of binaries and can be ignored as in the end of this page: http://www.linuxfromscratch.org/lfs/view/development/chapter06/strippingagain.html

A suggestion is that we can check if the file is script or binary in order to execute the strip command or not.

BR,

**Comment by FreddieChopin** [comment]
I was asking about the last part of your error message:
```
********** Package
Killed%        49,2 MiB / 316,3 MiB = 0,156   7,5 MiB/s       0:42             
tar: arm-none-eabi-gcc-8.2.0-180829.tar.xz: Wrote only 4096 of 10240 bytes
tar: Child returned status 137
tar: Error is not recoverable: exiting now
```

I'm wondering what caused the compression step to be killed here. If you did that manually because you saw the warnings above, then it's nothing. But maybe there's some other problem in here that caused `tar` to exit.

The "File format not recognized" warning message is something which is expected. I'll try to hide that somehow in the next release of the script, as this can indeed be misleading.

**Comment by l4es** [comment]
No, I didn't kill anything. I thought that was the consequence of strip however.

**Comment by FreddieChopin** [comment]
Hmm... This is strange then. Did you run the script again and it worked fine this time, or maybe you are just using the toolchain from `installNative/` folder?

**Comment by l4es** [comment]
This is systematic on my Ubuntu 18.04. I'm just using the toolchain under installNative/ folder because the re-compilation takes time. But I think the problem is probably around the following line in the script:

```
ln -s ${installNative} ${package}
...
XZ_OPT=${XZ_OPT-"-9e -T 0 -v"} tar -cJf ${packageArchiveNative} --group=0 --owner=0 $(find ${package}/ -mindepth 1 -maxdepth 1)
```
I will investigate more when having time.
